# Generated by Django 2.1.5 on 2019-05-21 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('POWER', 'power'), ('HAND', 'hand')], max_length=250)),
                ('work_field', models.CharField(choices=[('WOODWORKING', 'woodworking'), ('GARDEN', 'garden'), ('MECHANICAL', 'mechanical')], max_length=250)),
                ('manufacturer', models.CharField(max_length=250)),
                ('replacement_cost', models.CharField(max_length=250)),
                ('URL', models.TextField()),
                ('condition', models.TextField()),
                ('borrowed', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
