# Generated by Django 2.1.5 on 2019-05-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
